name: MkDocs Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install poetry
        run: |
          python -m pip install poetry==1.3.2

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install
      # - name: Install requirements
      #   run: |
      #     pip install -r requirements.txt
      # - name: Update last changed
      #   run: |
      #     python3 .github/scripts/last_changed.py
      - name: Build and deploy
        working-directory: .
        run: mkdocs gh-deploy --force --clean --verbose
