name: Check software versions

on:
  push:
    branches: [main]
  schedule:
    - cron: "28 0,12 * * *"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run software versions check
        run: |
          python src/versions/check_versions.py README.md
      - name: Update README.md
        uses: EndBug/add-and-commit@v9
        with:
          add: '["README.md", "versions.json"]'
          message: "Updated README.md software versions"
